version: '3.8'

services:
  mysql:
      image: mysql:5.7.30
      environment:
        MYSQL_ROOT_PASSWORD: prisma
      volumes:
        - ./docker/mysql:/var/lib/mysql
      ports:
        - "3333:3306"